config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'pages/home'

  get 'pages/about_us'
  get 'pages/admin'
  get 'pages/faq'
  get 'pages/contact'
  get 'pages/interact'
  get 'pages/home'
  get 'pages/marketingconsulting'
  get 'pages/jpmicrosite'
  get 'pages/checkoutclt'
  get 'pages/checkoutclt2'
  get 'pages/interactivecampaigns'
  get 'pages/cltquiz'
  get 'pages/cltcontest'
  root 'pages#newhome'
  get 'pages/reputationmanagement'
  get 'pages/newhome'

    resources :posts
    resources :campaigns

    match '/contacts', to: 'contacts#new', via: 'get'
resources "contacts", only: [:new, :create]

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	belongs_to :user

	GOAL = %w[inspire entertain educate custom]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,    :validate => true
  attribute :nickname,  :captcha  => true
  attribute :status 

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "330 Monday Contacts",
      :to => "info@330monday.com",
      :from => %("#{name}" <#{email}>)
    }
  end

  STATUS = %w[$1k-5k $5k-10k $10k-20k $20k-50k]

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user

	POSTTYPES = %w[work news fact image video blog]

	has_attached_file :image, :styles => { :large => "600x600#", :medium => "400x400#", :small => "200x200#" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :campaigns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	before_action :find_campaign, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@campaigns = Campaign.all.order("created_at DESC")
	end

	def show
		#@lyrics = Lyric.where(campaign_id: @campaign.id).order(:cached_votes_up => :desc)
		#@arts = Art.where(campaign_id: @campaign.id).order(:cached_weighted_total => :desc)

	end

	def new
		@campaign = current_user.campaigns.build
	end

	def create
		
		@campaign = current_user.campaigns.build(campaign_params)

		if @campaign.save
			redirect_to @campaign
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if @campaign.update(campaign_params)
			redirect_to @campaign
		else
			render 'edit'
		end

	end

	def destroy
		@campaign.destroy
		redirect_to root_path
	end


	private

	def find_campaign
		@campaign = Campaign.find(params[:id])
	end

	def campaign_params
		params.require(:campaign).permit(:title, :goal, :objectives, :consulting, :ideas, :focus, :brandwork, :totalbudget, :retainerbudget)
	end



	
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
  
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      redirect_to 'new'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_us
  end

  def admin
  end

    def interact

  end
    def faq
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
	    @posts = Post.all.order("RANDOM()")

	end

	def show

		@random_posts = Post.where.not(id: @post).order("RANDOM()").take(5)

		if @post == Post.last
			@next_post = Post.order(id: :asc).first
		else
			@next_post = Post.where("id > ?", @post).order(id: :asc).first
		end

		if @post == Post.first
			@previous_post = Post.order(id: :asc).last
		else
			@previous_post = Post.where("id < ?", @post).order(id: :desc).first
		end
		
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :description, :posttype, :image, :link)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign do |f| %>

      <%= f.error_notification %>

   <%= f.input :title, label: "Let's Title This Campaign" %>
    <%= f.input :goal, label: "Link To Artist for Credit" %>

<% f.radio_button :goal, label: "inspire", value: "inspire" do  %>
<img src="http://placehold.it/20x20/35d/fff&text=f">
<% end %>

<%= f.radio_button :goal, label: "educate", value: "educate" %>
<%= f.radio_button :goal, label: "entertain", value: "entertain" %>
<%= f.radio_button :goal, label: "custom", value: "custom" %>

      <label>
    <input type="radio" name="inspire" value="inspire" />
    <img src="http://placehold.it/20x20/35d/fff&text=f">
  </label>
  
  <label>
    <input type="radio" name="educate" value="educate"/>
    <img src="http://placehold.it/40x60/35d/fff&text=f">
  </label>
  
  <label>
    <input id="fb3" type="radio" name="entertain" value="entertain" />
    <img src="http://placehold.it/40x40/35d/fff&text=f">
  </label>
  
  <label>
    <input id="fb4" type="radio" name="custom" value="custom" />
    <img src="http://placehold.it/60x15/35d/fff&text=f">
  </label>

  <%= f.input :objectives, label: "Title" %>
  <%= f.input :consulting, label: "Tell us more" %>
   <%= f.input :ideas, label: "Enter rules" %>
   <%= f.input :focus, label: "Enter rewards" %>
  <%= f.input :brandwork, label: "Time for Lyric Submission" %>
  <%= f.input :totalbudget, label: "Time for Design Submission" %>
    <%= f.input :retainerbudget, label: "Time for Design Submission" %>

  <%= f.button :submit, "Submit", class: "button" %>



<% end %>

app/views/campaigns/new.html.erb
<%= render 'form' %>

app/views/contacts/create.html.erb
<div class="contact-ty">
<div class="skinny_wrapper wrapper_padding">
	
    <h1>Thank you for your message!</h1>
    <p>We will get back to you soon.</p>

</div>
</div>

app/views/layouts/_header.html.erb
<nav id="330header" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag '330monday-logo.png', :class => "logo-head2" %>
        
      <% end %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to 'Play', pages_interact_path %></li>
        <li>
          <%= link_to 'About Us', pages_about_us_path %>
        </li>

         <li><%= link_to 'Contact', pages_about_us_path(:anchor => "contact1") %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header2.html.erb
<nav id="330header" class="navbar navbar-default">

          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag '330monday-logo2.png', :class => "logo-head2" %>
        
      <% end %>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <% if false %>
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to 'Play', pages_interact_path %></li>
        <li>
          <%= link_to 'About Us', pages_about_us_path %>
        </li>

         <li><%= link_to 'Contact', pages_about_us_path(:anchor => "contact1") %></li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->

</nav>

app/views/layouts/_newheader.html.erb
<nav id="330header" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag '330monday-logo2.png', :class => "logo-head2" %>
        
      <% end %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to 'Reputation Management', pages_reputationmanagement_path %></li>

         <li><%= link_to '704.806.0760', '#' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>330Monday</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width" />

  
  <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" media="all" rel="stylesheet" type="text/css" />
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" media="all" rel="stylesheet" type="text/css" />

   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<script src="//use.typekit.net/xtv1vzx.js"></script>
<script>try{Typekit.load();}catch(e){}</script>

<script src="fabric.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64635628-1', 'auto');
  ga('send', 'pageview');

</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54468573-1', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>

       <% if current_page?(pages_checkoutclt_path) || current_page?(pages_checkoutclt2_path) || current_page?(pages_cltquiz_path) || current_page?(pages_cltcontest_path) %>

       <% elsif current_page?(root_path) || current_page?(pages_home_path) || current_page?(pages_newhome_path) %>
              <%= render 'layouts/newheader' %>
        <% else %>
            
        <% end %>


<%= yield %>

</body>
</html>

<script>
  $(function() {
     $('.flash-message').delay(500).fadeIn('normal', function() {
        $(this).delay(2500).fadeOut();
     });
  });
  </script>

app/views/pages/admin.html.erb
<h1>Admin Page</h1>

<% if user_signed_in? %>

<% else %>

<p>
	<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default btn-lg" %>
</p>
<% end %>

app/views/pages/home.html.erb
				<div id="homecontact">
					<%= link_to pages_about_us_path(:anchor => "contact1") do %>
					<button class="contact-button">
						Contact Today
					</button>
					<% end %>
				</div>

<div class="bscontainer-fluid">
	<div class="bsrow">


	<div id="demo-wrapper" class="">
		<div id="demo-canvas">



			<div class="centertop">
				<div class="title-home">
					<h1>Customer Engagement</br> And Interactions,</br> Done Right!</h1>

					<div class="image-part1">
						<%= image_tag 'bike-shape.svg', :class => "bikeimage" %>
					</div>

					
				</div>

			</div>

			<div id="exhibit-menu">
				<div id="exhibitwrap" class="">

					<div id="exhibitcircle">
						<span class="">INTERACT</span>
					
						<%= image_tag 'arrow_exhibit.png', :class => "", id: "arrowexhibit" %>
					</div>

					<div id="exhibit-content">
						<h2>
							Interactive & Engaging </br>Campaigns
						</h2>
						<ul id="exhibitside">
						<li>Interactive exhibits for festivals.</li>
						<li>Micro content for social media.</li>
						<li>Microsites for new sales.</li>
						</ul>
						<%= link_to 'Learn More', pages_interactivecampaigns_path, :class => "learnmore" %>

						<%= link_to pages_about_us_path(:anchor => "contact1") do %>
							<button id="contact-exhibit" class="contact-button">
							Contact Today
							</button>
						<% end %>
					</div>

				</div>

			</div>
			<div id="partner-menu">
				<div id="partnerwrap" class="">

					<div id="partnercircle">
						<span class="">CONSULT</span>

						<%= image_tag 'arrow_partner.png', :class => "", id: "arrowpartner" %>
					</div>

					<div id="partner-content">
					<h2>
							Communication & Marketing</br> Consulting
						</h2>
						<ul id="partnerside">
						<li>Overall marketing strategies.</li>
						<li>Training of new marketing channels.</li>
						<li>Evaluate and analyze current plan..</li>
						</ul>
						<%= link_to 'Learn More', pages_marketingconsulting_path, :class => "learnmore" %>

						<%= link_to pages_about_us_path(:anchor => "contact1") do %>
							<button id="contact-partner" class="contact-button">
								Contact Today
							</button>
						<% end %>
					</div>

				</div>
				
			</div>


		</div>

	</div>

</div>
</div>

<section class="blog-section nodisplay">
	<div class="learnhow-box">
		<div class="learnhow-boxleft">
			<h1>Our Marketing Strategy is Simple.</h1>
			<h2>Go where the eyeballs are.</h2>

			<div class="learnhow-button">	
				Learn how to reach your market.

			</div>
		</div>
		<div class="learnhow-boxright">
			<%= image_tag 'oktoberfest5.JPG', :class => "learnbox-image" %>
		</div>
	</div>

	<div class="happy-box">
		<h1>Our Focus is Happiness.</h1>
		<h2>Communication is about</br>finding what makes people happy.</h2>


	</div>

	<div class="blogpost-section">

		<div class="blog-post">
			<div class="img-box">

				<%= image_tag 'oktoberfest5.JPG', :class => "learnbox-image" %>

			</div>
			<div class="blog-title">
				How to market at events.

			</div>


		</div>

		<div class="blog-post">
			<div class="img-box">

				<%= image_tag 'oktoberfest5.JPG', :class => "learnbox-image" %>

			</div>
			<div class="blog-title">
				How to interact with customers.

			</div>


		</div>

		<div class="blog-post">
			<div class="img-box">

				<%= image_tag 'oktoberfest5.JPG', :class => "learnbox-image" %>

			</div>
			<div class="blog-title">
				Top needs for your online presence.

			</div>


		</div>

		<div class="blog-post">
			<div class="img-box">

				<%= image_tag 'oktoberfest5.JPG', :class => "learnbox-image" %>

			</div>
			<div class="blog-title">
				How to stay focus on your goals.

			</div>


		</div>


	</div>



	</section>

	<section class="services-section nodisplay">

		<h1>WE HANDLE ALL OF</br>YOUR MARKETING AND</br>COMMUNICATIONS NEEDS.</h1>

		<div class="categories">
		<div class="service-category">
			<%= image_tag 'services-face.jpg', :class => "category-image" %>

			<div class="category-box">
				<h2>Face To Face</h1>

					<p>We provide interactive solutions to engage future customers at festivals, tradeshows and events.  Also provide solutions for in house events and sponsorship partnerships.</p>

					<button class="learn-button">
						Learn More
					</button>


			</div>


		</div>

				<div class="service-category">
			<%= image_tag 'services-social.jpg', :class => "category-image" %>

			<div class="category-box">
				<h2>Communication</h1>

					<p>We provide solutions to connect to your target market online and offline.  We help you develop a message to use on social media and in other tradition channels.</p>

					<button class="learn-button">
						Learn More
					</button>


			</div>


		</div>

				<div class="service-category">
			<%= image_tag 'services-web.jpg', :class => "category-image" %>

			<div class="category-box">
				<h2>Web Presense</h1>

					<p>We provide simple solutions to showcase your brand and make a great first impression online.  We make sure your business looks professional and consistent on all devices.</p>

					<button class="learn-button">
						Learn More
					</button>


			</div>


		</div>


	</div>

	</section>

<script>
/// mobile adjustment
$("#exhibitcircle").click(function(){
	$("#demo-wrapper").toggleClass("show-nav2");
	$("#exhibitcircle span").toggleClass("opacity");
	$("#arrowexhibit").toggleClass("clockwise180");
	$("#homecontact").toggleClass("nodisplay");
});
$("#partnercircle").click(function(){
	$("#demo-wrapper").toggleClass("show-nav");
	$("#partnercircle span").toggleClass("opacity");
	$("#arrowpartner").toggleClass("clockwise180");
	$("#homecontact").toggleClass("nodisplay");
});

//When you hover over partner circle, you add class show-nav to wrapper demo
//select cirlce
$("#exhibit-menu").mouseenter(function(){
	$("#demo-wrapper").addClass("show-nav2");
	$("#exhibitcircle span").addClass("opacity");
	$("#arrowexhibit").addClass("clockwise180");
	$("#homecontact").addClass("nodisplay");
});
$("#exhibit-menu").mouseleave(function(){
	$("#demo-wrapper").removeClass("show-nav2");
	$("#exhibitcircle span").removeClass("opacity");
	$("#arrowexhibit").removeClass("clockwise180");
	$("#homecontact").removeClass("nodisplay");
});

$("#partner-menu").mouseenter(function(){
	$("#demo-wrapper").addClass("show-nav");
	$("#partnercircle span").addClass("opacity");
	$("#arrowpartner").addClass("clockwise180");
	$("#homecontact").addClass("nodisplay");
});
$("#partner-menu").mouseleave(function(){
	$("#demo-wrapper").removeClass("show-nav");
	$("#partnercircle span").removeClass("opacity");
	$("#arrowpartner").removeClass("clockwise180");
	$("#homecontact").removeClass("nodisplay");
});





//add class show-nav to wrapper demo
//how to do smooth tranisition
//stay on section long as hover over partner section
//move back to center section
//take class show-nav off wrapper demo

//When you haver over exhibit circle, you add class show-nav2 to wrapper demo



</script>



app/views/pages/interactivecampaigns.html.erb
<div class="bscontainer-fluid">
	<div class="bsrow">

			<div class="exhibits-section">

				<h1>WE CREATE AWESOME</br>INTERACTIVE CAMPAIGNS</br>THAT WIN CUSTOMERS OVER.</h1>

				<div class="campaignbox">
					<%= image_tag 'campaign1.png', :class => "campaignimages" %>

					<div class="campaign-info">

					We love to start a campaign with Face To Face contact by developing cool <span class="campaigninfo1" id="goexhibits">Exhibitions</span> that connect with specific cultures.

				</div>

				</div>
				<div class="campaignbox">
					<%= image_tag 'campaign3.png', :class => "campaignimages" %>

					<div class="campaign-info">

					We then create interactive and engaging movements on <span class="campaigninfo2" id="gosocial">Social Media</span> to continue to build relationships with customers.


				</div>

				</div>
				<div class="campaignbox">
					<%= image_tag 'campaign2.png', :class => "campaignimages" %>
					<div class="campaign-info">

				 We bring it all together by creating a <span class="campaigninfo3" id="gomicro">Microsite</span> that gives better opportunity to create leads, build communites or closed sales.


				</div>

				</div>
				
				
				
				

				


			</div>

			<div class="exhibits1">

					<div class="image-part1">
						<%= image_tag 'greenbike-shape.svg', :class => "bikeimage" %>
					</div>

					<div class="exhibits-info">
						<div class="exhibits-title">Interactive Exhibits</div>

						<div class="exhibits-para">
							<p>We develop interactive exhibit concepts that get guest to wonder whats going on at your booth.  No more sitting behind a table and running customers away. Our exhibits are visualy appealing and always include an interactive component so guests can connect with your brand on an emotional level.</p>

							<p>We also provide unique event concepts that push to engage guests on another level.</p>

							<p>All of our interactive exhibits include an interactive part to inspire, educate or entertain guests.</p>

							<p>Examples: Art wall, educational games, interactive product demos, do it yourself showcase, engaging contests, etc.</p>

						</div>


					</div>


			</div>


			<div class="socialmedia1">


					<div class="socialmedia-info">
						<div class="socialmedia-title">Interactive Social Media</div>

						<div class="socialmedia-para">
							<p>We develop marketing strategies and campaigns to take face to face connections to online connections.  We provide micro content for social media accounts to increase engagement and connections.</p>

							<p>Micro content is pics and videos that is designed specifically for different social media platforms.</p>

							<p>All of our micro content include an interactive part to inspire, educate or entertain guests.</p>

							<p>Examples: Quotes, facts, infographics, short video clips, interviews, photo series, customer content creation, brand inspired content, event recaps, etc.</p>
						</div>


					</div>

					<div class="image-part1">
						<%= image_tag 'yellowbike-shape.svg', :class => "bikeimage" %>
					</div>


			</div>

				<div class="microsite1">

					<div class="image-part1">
						<%= image_tag 'bike-shape.svg', :class => "bikeimage2" %>
					</div>

					<div class="microsite-info">
						<div class="microsite-title">Interactive Microsite</div>

						<div class="microsite-para">
							<p>We provide microsites that are great to bring customers to your product or service.  We provide ways to gain more info from customers and opportunity to gain sales and grow leads.</p>

							<p>A micorsite is basically a mini site outside your primary website to promote a campaign, connect to new markets or showcase new products.</p>

							<p>All of our microsites include an interactive part to inspire, educate or entertain guests.</p>

							<p>Examples: Quizzes, surveys, games, contests, giveaways, event participation, 
							meme/social media generator, interative infographics, etc.</p>

						</div>


					</div>


			</div>

				<div id="bottomcontact">
					<%= link_to pages_about_us_path(:anchor => "contact1") do %>
					<button class="contact-button">
						Contact Today
					</button>
					<% end %>
				</div>



	</div>
</div>


<script>
//When you hover over partner circle, you add class show-nav to wrapper demo
//select cirlce
$("#exhibit-menu2").mouseenter(function(){
	$("#demo-wrapper2").addClass("show-nav2");
	$("#exhibitcircle2 span").addClass("opacity");
	$("#arrowexhibit2").addClass("clockwise180");
});
$("#exhibit-menu2").mouseleave(function(){
	$("#demo-wrapper2").removeClass("show-nav2");
	$("#exhibitcircle2 span").removeClass("opacity");
	$("#arrowexhibit2").removeClass("clockwise180");
});

$("#partner-menu2").mouseenter(function(){
	$("#demo-wrapper2").addClass("show-nav");
	$("#partnercircle2 span").addClass("opacity");
	$("#arrowpartner2").addClass("clockwise180");
});
$("#partner-menu2").mouseleave(function(){
	$("#demo-wrapper2").removeClass("show-nav");
	$("#partnercircle2 span").removeClass("opacity");
	$("#arrowpartner2").removeClass("clockwise180");
});


//add class show-nav to wrapper demo
//how to do smooth tranisition
//stay on section long as hover over partner section
//move back to center section
//take class show-nav off wrapper demo

//When you haver over exhibit circle, you add class show-nav2 to wrapper demo



</script>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>


<%= link_to 'Posts', posts_path, class: "back-button" %>

app/views/posts/index.html.erb
 <section class="homepage-back">
  <div id="posts">
    <% @posts.each do |post| %>
    <div class="container-post-index">

		<% unless post.image.nil? || post.image.blank? %>
			
        <%= link_to post_path(post) do %>
				  <%= image_tag post.image.url(:small) %>
        <% end %>
	
		<% end %>

     
      
      </div>
    <% end %>
  </section>



    

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>


<%= link_to 'Posts', posts_path, class: "back-button" %>

app/views/posts/show.html.erb
<section class="post-section">
    <div class="stepbackward">
    			<%= link_to post_path(@previous_post) do %>
    				<span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
    			<% end %>
    		</div>
    		<div class="stepforward">
    			<%= link_to post_path(@next_post) do %>
    				<span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span>
    			<% end %>
    			</div>
    <div class="container-show">
    	
    	<div class="container-post">

        <% if @post.title.present? %>
    		<h1><%= @post.title %></h1>
        <% end %>
    
    				<%= image_tag @post.image.url(:small) %>
    



    	</div>
    



       <% unless @post.description.nil? || @post.description.empty? %>
    	<div class="container-post-desc">
    		 
    		<%= simple_format(@post.description) %>
    	</div>
    	<% end %>

    	<% if user_signed_in? %>
    		<%= link_to 'Edit', edit_post_path(@post) %> | 
    		
    		<%= link_to 'Destroy', [@post], method: :delete, data: {confirm: "Are you sure?" } %>
    		<% end %>
    		
    </div>
 </section>